name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          cache: sbt
          java-version: 11
      - name: Build and Test
        run: sbt -v +test
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "test-results/**/TEST-*.xml"
        if: always()

