name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK and sbt
        uses: guardian/setup-scala@v1
      - name: Build and Test
        run: sbt -v +test
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "test-results/**/TEST-*.xml"
        if: always()

